# ========================================
# 1. CỔNG 1883 DÀNH CHO BACKEND VÀ YOLO UNO
# ========================================
listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/pwfile

# ========================================
# 2. CỔNG 9001 DÀNH CHO WEBSOCKETS (FRONTEND)
# ========================================
listener 9001 0.0.0.0
protocol websockets
allow_anonymous false
password_file /mosquitto/config/pwfile

# ========================================
# 3. LƯU TRỮ VÀ NHẬT KÝ
# ========================================
persistence true
persistence_file mosquitto.db
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

listener 1883 0.0.0.0
allow_anonymous true